// AUTO-GENERATED by scripts/gen-deployments.mjs — DO NOT EDIT BY HAND.
// Regenerate with `node scripts/gen-deployments.mjs` (runs on prebuild).
// Source: broadcast/DeployAll.s.sol/<chainId>/run-latest.json + out/<C>.sol/<C>.json.

/** The normalized current-build runtime-code fingerprint for one contract. */
export interface ContractBytecode {
  /** keccak256 of the metadata-stripped, immutable-zeroed runtime code. */
  readonly codeHash: `0x${string}`
  /** Immutable byte ranges [startByte, lengthBytes] to zero before comparing
   *  on-chain code (the constructor bakes these in; the artifact leaves zeros). */
  readonly immutableRanges: ReadonlyArray<readonly [number, number]>
}

/** contractName -> its current-build fingerprint. The dashboard compares the
 *  on-chain hash (computed the SAME way) against these. */
export const CURRENT_BYTECODE: Readonly<Record<string, ContractBytecode>> = {
  "Access0x1Bookings": {
    "codeHash": "0x6ad5ad46524701e01afd5989d1a37ab815239340f16e20ad5689c17ce161607c",
    "immutableRanges": [
      [
        5128,
        32
      ],
      [
        5331,
        32
      ]
    ]
  },
  "Access0x1Escrow": {
    "codeHash": "0x35064850c85d09621c40faf9f0965c185518ee65be76e5f4c9732d5c9b218328",
    "immutableRanges": [
      [
        1777,
        32
      ],
      [
        2385,
        32
      ]
    ]
  },
  "Access0x1GiftCards": {
    "codeHash": "0x42ab591b5ee37d985da6d1a55353c4adb6009c7a6cecfdc84882b37b42c50706",
    "immutableRanges": [
      [
        2634,
        32
      ],
      [
        3194,
        32
      ]
    ]
  },
  "Access0x1Invoices": {
    "codeHash": "0x418c064aa2d8275b583df66524198911f43b6c77b6e87ff70208d0958710bc67",
    "immutableRanges": [
      [
        3200,
        32
      ],
      [
        3404,
        32
      ]
    ]
  },
  "Access0x1Nft": {
    "codeHash": "0x3e1916dd5d79b20e4214d65d642d4dbc10cb0188d15edfc018ad138452bda185",
    "immutableRanges": [
      [
        1162,
        32
      ],
      [
        1384,
        32
      ]
    ]
  },
  "Access0x1ProvenanceRegistry": {
    "codeHash": "0xcf9c8ed5221dc76be8fc87612ccf261fbeef56e05befcac2d94a67464d48fd7f",
    "immutableRanges": [
      [
        2255,
        32
      ],
      [
        2502,
        32
      ]
    ]
  },
  "Access0x1Router": {
    "codeHash": "0xd29606cc6661991f348792f57082f871dbcd6fe54d1c69153cfc127b503c46bd",
    "immutableRanges": [
      [
        5217,
        32
      ],
      [
        5421,
        32
      ]
    ]
  },
  "Access0x1Subscriptions": {
    "codeHash": "0x9da6998ae4dcc2934b47f809b5fee696c7337bd9d552b923c5bd9a16dc126c9e",
    "immutableRanges": [
      [
        2854,
        32
      ],
      [
        6301,
        32
      ]
    ]
  },
  "AutomationGateway": {
    "codeHash": "0x85c5b99adc0e9fcfae69da5843d845e8b4c484716aafe3ea680a8cc078475b1f",
    "immutableRanges": [
      [
        1561,
        32
      ],
      [
        1765,
        32
      ]
    ]
  },
  "ERC1967Proxy": {
    "codeHash": "0x46a010df31eb642b47284650e80051e8f6239a0c995003d230b437810bc4b9b4",
    "immutableRanges": []
  },
  "HouseTokenFactory": {
    "codeHash": "0xfafac3c889816f10ab260dd513909e90f5d669dd4d5a156a56e3a36a30047b2d",
    "immutableRanges": [
      [
        2462,
        32
      ],
      [
        2680,
        32
      ]
    ]
  },
  "PaymentLanes": {
    "codeHash": "0xc8e029cd9f78ee11036865676ec65e3435461321222496e01e081e9aec65e78a",
    "immutableRanges": [
      [
        2511,
        32
      ],
      [
        2731,
        32
      ]
    ]
  },
  "SessionGrant": {
    "codeHash": "0x96eb3e034ffdb7fcb0464a19061ddaaf2c2a8961925f66ceb464368a24431883",
    "immutableRanges": [
      [
        2257,
        32
      ],
      [
        2403,
        32
      ]
    ]
  }
} as const
