// AUTO-GENERATED by scripts/gen-deployments.mjs — DO NOT EDIT BY HAND.
// Regenerate with `node scripts/gen-deployments.mjs` (runs on prebuild).
// Source: broadcast/DeployAll.s.sol/<chainId>/run-latest.json + out/<C>.sol/<C>.json.

/** The normalized current-build runtime-code fingerprint for one contract. */
export interface ContractBytecode {
  /** keccak256 of the metadata-stripped, immutable-zeroed runtime code. */
  readonly codeHash: `0x${string}`
  /** Immutable byte ranges [startByte, lengthBytes] to zero before comparing
   *  on-chain code (the constructor bakes these in; the artifact leaves zeros). */
  readonly immutableRanges: ReadonlyArray<readonly [number, number]>
}

/** contractName -> its current-build fingerprint. The dashboard compares the
 *  on-chain hash (computed the SAME way) against these. */
export const CURRENT_BYTECODE: Readonly<Record<string, ContractBytecode>> = {
  "Access0x1Bookings": {
    "codeHash": "0x6456d1e10a37863a5ba5c5be7bbb7027cbafe179213e73623d53171a6e1e116b",
    "immutableRanges": [
      [
        5158,
        32
      ],
      [
        5361,
        32
      ]
    ]
  },
  "Access0x1Bookings.impl": {
    "codeHash": "0x6456d1e10a37863a5ba5c5be7bbb7027cbafe179213e73623d53171a6e1e116b",
    "immutableRanges": [
      [
        5158,
        32
      ],
      [
        5361,
        32
      ]
    ]
  },
  "Access0x1Bookings.proxy": {
    "codeHash": "0x46a010df31eb642b47284650e80051e8f6239a0c995003d230b437810bc4b9b4",
    "immutableRanges": []
  },
  "Access0x1Escrow": {
    "codeHash": "0x35064850c85d09621c40faf9f0965c185518ee65be76e5f4c9732d5c9b218328",
    "immutableRanges": [
      [
        1777,
        32
      ],
      [
        2385,
        32
      ]
    ]
  },
  "Access0x1Escrow.impl": {
    "codeHash": "0x35064850c85d09621c40faf9f0965c185518ee65be76e5f4c9732d5c9b218328",
    "immutableRanges": [
      [
        1777,
        32
      ],
      [
        2385,
        32
      ]
    ]
  },
  "Access0x1Escrow.proxy": {
    "codeHash": "0x46a010df31eb642b47284650e80051e8f6239a0c995003d230b437810bc4b9b4",
    "immutableRanges": []
  },
  "Access0x1GiftCards": {
    "codeHash": "0x42ab591b5ee37d985da6d1a55353c4adb6009c7a6cecfdc84882b37b42c50706",
    "immutableRanges": [
      [
        2634,
        32
      ],
      [
        3194,
        32
      ]
    ]
  },
  "Access0x1GiftCards.impl": {
    "codeHash": "0x42ab591b5ee37d985da6d1a55353c4adb6009c7a6cecfdc84882b37b42c50706",
    "immutableRanges": [
      [
        2634,
        32
      ],
      [
        3194,
        32
      ]
    ]
  },
  "Access0x1GiftCards.proxy": {
    "codeHash": "0x46a010df31eb642b47284650e80051e8f6239a0c995003d230b437810bc4b9b4",
    "immutableRanges": []
  },
  "Access0x1Invoices": {
    "codeHash": "0x418c064aa2d8275b583df66524198911f43b6c77b6e87ff70208d0958710bc67",
    "immutableRanges": [
      [
        3200,
        32
      ],
      [
        3404,
        32
      ]
    ]
  },
  "Access0x1Invoices.impl": {
    "codeHash": "0x418c064aa2d8275b583df66524198911f43b6c77b6e87ff70208d0958710bc67",
    "immutableRanges": [
      [
        3200,
        32
      ],
      [
        3404,
        32
      ]
    ]
  },
  "Access0x1Invoices.proxy": {
    "codeHash": "0x46a010df31eb642b47284650e80051e8f6239a0c995003d230b437810bc4b9b4",
    "immutableRanges": []
  },
  "Access0x1Nft": {
    "codeHash": "0x3e1916dd5d79b20e4214d65d642d4dbc10cb0188d15edfc018ad138452bda185",
    "immutableRanges": [
      [
        1162,
        32
      ],
      [
        1384,
        32
      ]
    ]
  },
  "Access0x1Nft.impl": {
    "codeHash": "0x3e1916dd5d79b20e4214d65d642d4dbc10cb0188d15edfc018ad138452bda185",
    "immutableRanges": [
      [
        1162,
        32
      ],
      [
        1384,
        32
      ]
    ]
  },
  "Access0x1Nft.proxy": {
    "codeHash": "0x46a010df31eb642b47284650e80051e8f6239a0c995003d230b437810bc4b9b4",
    "immutableRanges": []
  },
  "Access0x1ProvenanceRegistry": {
    "codeHash": "0xcf9c8ed5221dc76be8fc87612ccf261fbeef56e05befcac2d94a67464d48fd7f",
    "immutableRanges": [
      [
        2255,
        32
      ],
      [
        2502,
        32
      ]
    ]
  },
  "Access0x1ProvenanceRegistry.impl": {
    "codeHash": "0xcf9c8ed5221dc76be8fc87612ccf261fbeef56e05befcac2d94a67464d48fd7f",
    "immutableRanges": [
      [
        2255,
        32
      ],
      [
        2502,
        32
      ]
    ]
  },
  "Access0x1ProvenanceRegistry.proxy": {
    "codeHash": "0x46a010df31eb642b47284650e80051e8f6239a0c995003d230b437810bc4b9b4",
    "immutableRanges": []
  },
  "Access0x1Rebates.impl": {
    "codeHash": "0x31ee6ae038fef251b34a9aeb0277f793e54041529f675d1818eaab1b2f7e9b53",
    "immutableRanges": [
      [
        1807,
        32
      ],
      [
        2209,
        32
      ]
    ]
  },
  "Access0x1Rebates.proxy": {
    "codeHash": "0x46a010df31eb642b47284650e80051e8f6239a0c995003d230b437810bc4b9b4",
    "immutableRanges": []
  },
  "Access0x1Router": {
    "codeHash": "0xd29606cc6661991f348792f57082f871dbcd6fe54d1c69153cfc127b503c46bd",
    "immutableRanges": [
      [
        5217,
        32
      ],
      [
        5421,
        32
      ]
    ]
  },
  "Access0x1Router.impl": {
    "codeHash": "0xd29606cc6661991f348792f57082f871dbcd6fe54d1c69153cfc127b503c46bd",
    "immutableRanges": [
      [
        5217,
        32
      ],
      [
        5421,
        32
      ]
    ]
  },
  "Access0x1Router.proxy": {
    "codeHash": "0x46a010df31eb642b47284650e80051e8f6239a0c995003d230b437810bc4b9b4",
    "immutableRanges": []
  },
  "Access0x1SponsorRegistry.impl": {
    "codeHash": "0x1cf58f7095e1f92a1cafff94a70d2d2e2860d018999f4e6f78005208ca96e744",
    "immutableRanges": [
      [
        1252,
        32
      ],
      [
        1472,
        32
      ]
    ]
  },
  "Access0x1SponsorRegistry.proxy": {
    "codeHash": "0x46a010df31eb642b47284650e80051e8f6239a0c995003d230b437810bc4b9b4",
    "immutableRanges": []
  },
  "Access0x1Subscriptions": {
    "codeHash": "0xd7ed0198154a7ab2d0d0d88cd32945e2d6d6e20759f34a7a4ea3ab9f67fb0231",
    "immutableRanges": [
      [
        3063,
        32
      ],
      [
        7060,
        32
      ]
    ]
  },
  "Access0x1Subscriptions.impl": {
    "codeHash": "0xd7ed0198154a7ab2d0d0d88cd32945e2d6d6e20759f34a7a4ea3ab9f67fb0231",
    "immutableRanges": [
      [
        3063,
        32
      ],
      [
        7060,
        32
      ]
    ]
  },
  "Access0x1Subscriptions.proxy": {
    "codeHash": "0x46a010df31eb642b47284650e80051e8f6239a0c995003d230b437810bc4b9b4",
    "immutableRanges": []
  },
  "AutomationGateway": {
    "codeHash": "0x85c5b99adc0e9fcfae69da5843d845e8b4c484716aafe3ea680a8cc078475b1f",
    "immutableRanges": [
      [
        1561,
        32
      ],
      [
        1765,
        32
      ]
    ]
  },
  "AutomationGateway.impl": {
    "codeHash": "0x85c5b99adc0e9fcfae69da5843d845e8b4c484716aafe3ea680a8cc078475b1f",
    "immutableRanges": [
      [
        1561,
        32
      ],
      [
        1765,
        32
      ]
    ]
  },
  "AutomationGateway.proxy": {
    "codeHash": "0x46a010df31eb642b47284650e80051e8f6239a0c995003d230b437810bc4b9b4",
    "immutableRanges": []
  },
  "ERC1967Proxy": {
    "codeHash": "0x46a010df31eb642b47284650e80051e8f6239a0c995003d230b437810bc4b9b4",
    "immutableRanges": []
  },
  "GaslessPayIn.impl": {
    "codeHash": "0xb6cc92ccdea61ff90a56b197242e9f7a4d1469a86329f458251daf65cbfbd573",
    "immutableRanges": [
      [
        3078,
        32
      ],
      [
        3283,
        32
      ]
    ]
  },
  "GaslessPayIn.proxy": {
    "codeHash": "0x46a010df31eb642b47284650e80051e8f6239a0c995003d230b437810bc4b9b4",
    "immutableRanges": []
  },
  "HouseTokenFactory": {
    "codeHash": "0xfafac3c889816f10ab260dd513909e90f5d669dd4d5a156a56e3a36a30047b2d",
    "immutableRanges": [
      [
        2462,
        32
      ],
      [
        2680,
        32
      ]
    ]
  },
  "HouseTokenFactory.impl": {
    "codeHash": "0xfafac3c889816f10ab260dd513909e90f5d669dd4d5a156a56e3a36a30047b2d",
    "immutableRanges": [
      [
        2462,
        32
      ],
      [
        2680,
        32
      ]
    ]
  },
  "HouseTokenFactory.proxy": {
    "codeHash": "0x46a010df31eb642b47284650e80051e8f6239a0c995003d230b437810bc4b9b4",
    "immutableRanges": []
  },
  "PaymentLanes": {
    "codeHash": "0x8c97537cd784ea8cff72c6e5dd1e8728a53e12c0c936b27662a845a062af289e",
    "immutableRanges": [
      [
        2576,
        32
      ],
      [
        2796,
        32
      ]
    ]
  },
  "PaymentLanes.impl": {
    "codeHash": "0x8c97537cd784ea8cff72c6e5dd1e8728a53e12c0c936b27662a845a062af289e",
    "immutableRanges": [
      [
        2576,
        32
      ],
      [
        2796,
        32
      ]
    ]
  },
  "PaymentLanes.proxy": {
    "codeHash": "0x46a010df31eb642b47284650e80051e8f6239a0c995003d230b437810bc4b9b4",
    "immutableRanges": []
  },
  "PriceOracleAdapter.impl": {
    "codeHash": "0xdb045c6f0a383e7324d8ca539e07827d124f91883f29399ec3b12f7071faf7e2",
    "immutableRanges": [
      [
        1866,
        32
      ],
      [
        2298,
        32
      ]
    ]
  },
  "PriceOracleAdapter.proxy": {
    "codeHash": "0x46a010df31eb642b47284650e80051e8f6239a0c995003d230b437810bc4b9b4",
    "immutableRanges": []
  },
  "Receivables.impl": {
    "codeHash": "0x8c05bf1924fa99c0a65713d78f34b6a8422a9545dddf9334be47b2a2004cbcd9",
    "immutableRanges": [
      [
        7367,
        32
      ],
      [
        7513,
        32
      ]
    ]
  },
  "Receivables.proxy": {
    "codeHash": "0x46a010df31eb642b47284650e80051e8f6239a0c995003d230b437810bc4b9b4",
    "immutableRanges": []
  },
  "Refunds.impl": {
    "codeHash": "0x861803db5e70db9bc60237071d491a8ef79a3e55ae3171e7499342d2ed96944b",
    "immutableRanges": [
      [
        2757,
        32
      ],
      [
        3228,
        32
      ]
    ]
  },
  "Refunds.proxy": {
    "codeHash": "0x46a010df31eb642b47284650e80051e8f6239a0c995003d230b437810bc4b9b4",
    "immutableRanges": []
  },
  "SessionGrant": {
    "codeHash": "0x96eb3e034ffdb7fcb0464a19061ddaaf2c2a8961925f66ceb464368a24431883",
    "immutableRanges": [
      [
        2257,
        32
      ],
      [
        2403,
        32
      ]
    ]
  },
  "SessionGrant.impl": {
    "codeHash": "0x96eb3e034ffdb7fcb0464a19061ddaaf2c2a8961925f66ceb464368a24431883",
    "immutableRanges": [
      [
        2257,
        32
      ],
      [
        2403,
        32
      ]
    ]
  },
  "SessionGrant.proxy": {
    "codeHash": "0x46a010df31eb642b47284650e80051e8f6239a0c995003d230b437810bc4b9b4",
    "immutableRanges": []
  },
  "SplitSettler.impl": {
    "codeHash": "0xa6a758ca4ca911867d264441250addcff1ea3981a424a0ac48507b709ba44c19",
    "immutableRanges": [
      [
        5252,
        32
      ],
      [
        5724,
        32
      ]
    ]
  },
  "SplitSettler.proxy": {
    "codeHash": "0x46a010df31eb642b47284650e80051e8f6239a0c995003d230b437810bc4b9b4",
    "immutableRanges": []
  }
} as const
