// AUTO-GENERATED by scripts/gen-deployments.mjs — DO NOT EDIT BY HAND.
// Regenerate with `node scripts/gen-deployments.mjs` (runs on prebuild).
// Source: broadcast/DeployAll.s.sol/<chainId>/run-latest.json + out/<C>.sol/<C>.json.

/** The normalized current-build runtime-code fingerprint for one contract. */
export interface ContractBytecode {
  /** keccak256 of the metadata-stripped, immutable-zeroed runtime code. */
  readonly codeHash: `0x${string}`
  /** Immutable byte ranges [startByte, lengthBytes] to zero before comparing
   *  on-chain code (the constructor bakes these in; the artifact leaves zeros). */
  readonly immutableRanges: ReadonlyArray<readonly [number, number]>
}

/** contractName -> its current-build fingerprint. The dashboard compares the
 *  on-chain hash (computed the SAME way) against these. */
export const CURRENT_BYTECODE: Readonly<Record<string, ContractBytecode>> = {
  "Access0x1Bookings": {
    "codeHash": "0x7860c4f1894fbbaa72419030b7688e91812d00acb7d211ad27587bd590bda36f",
    "immutableRanges": [
      [
        381,
        32
      ],
      [
        1116,
        32
      ],
      [
        2952,
        32
      ],
      [
        4489,
        32
      ],
      [
        6223,
        32
      ],
      [
        7053,
        32
      ],
      [
        7750,
        32
      ],
      [
        7919,
        32
      ]
    ]
  },
  "Access0x1GiftCards": {
    "codeHash": "0x227d276a18558b2b36ec717e71d824b95a9e6add78230de194d7ec659d0e96b5",
    "immutableRanges": [
      [
        246,
        32
      ],
      [
        865,
        32
      ],
      [
        1505,
        32
      ],
      [
        2190,
        32
      ],
      [
        3241,
        32
      ],
      [
        4241,
        32
      ]
    ]
  },
  "Access0x1Invoices": {
    "codeHash": "0x3f4f41e91307bc761bd31cdd0b03330e59feb7c0abfb321281aafe5678de1751",
    "immutableRanges": [
      [
        139,
        32
      ],
      [
        311,
        32
      ],
      [
        1555,
        32
      ],
      [
        3126,
        32
      ]
    ]
  },
  "Access0x1Nft": {
    "codeHash": "0x373092dc5f0316efba5d498c08575f2b4be640c43cf78d3448080e47401314b0",
    "immutableRanges": [
      [
        212,
        32
      ],
      [
        1168,
        32
      ],
      [
        2602,
        32
      ]
    ]
  },
  "Access0x1Router": {
    "codeHash": "0x86e2905640c5266fde045d3320751e07902bdbd54dd2c5bd1625158ff919e4d9",
    "immutableRanges": []
  },
  "Access0x1Subscriptions": {
    "codeHash": "0x7dbdc7bf2b0392e04f5dce2858c5ef34e5c1288d50c031fc15a093df345cb401",
    "immutableRanges": [
      [
        493,
        32
      ],
      [
        979,
        32
      ],
      [
        1358,
        32
      ],
      [
        2775,
        32
      ],
      [
        3910,
        32
      ],
      [
        5338,
        32
      ],
      [
        5814,
        32
      ],
      [
        5905,
        32
      ],
      [
        7223,
        32
      ],
      [
        7316,
        32
      ]
    ]
  },
  "HouseTokenFactory": {
    "codeHash": "0x74fc637fd7d6e4d21fcd07c0bfa44fff5c2f2e97ce21ad289948d10055e04f30",
    "immutableRanges": []
  },
  "PaymentLanes": {
    "codeHash": "0x2e508e04d8bb81fbf3587926e83bfd6b8c5760a7a92381623ae678469e8d6541",
    "immutableRanges": []
  },
  "SessionGrant": {
    "codeHash": "0x8767a1e22986ebfd71ea14b6cc1894ab7832ec0efb6cf64b558949fea6b87995",
    "immutableRanges": [
      [
        1103,
        32
      ],
      [
        1144,
        32
      ],
      [
        3651,
        32
      ],
      [
        3705,
        32
      ],
      [
        3784,
        32
      ],
      [
        3822,
        32
      ],
      [
        3888,
        32
      ]
    ]
  }
} as const
