// AUTO-GENERATED by scripts/gen-deployments.mjs — DO NOT EDIT BY HAND.
// Regenerate with `node scripts/gen-deployments.mjs` (runs on prebuild).
// Source: broadcast/DeployAll.s.sol/<chainId>/run-latest.json + out/<C>.sol/<C>.json.

/** Display + deep-link metadata and the CREATE deployments for one chain. */
export interface ChainDeployments {
  /** EIP-155 chain id. */
  readonly chainId: number
  /** Human chain name (from the canonical viem chain object, or Arc inline). */
  readonly name: string
  /** Block-explorer base url (no trailing slash), or undefined when none is known
   *  — the UI then renders the address as plain text, never an invented link. */
  readonly explorer?: string
  /** A public RPC fallback for this chain (overridden by NEXT_PUBLIC_RPC_URL_<id>). */
  readonly rpc?: string
  /** The contracts this chain deployed: { contractName, address } per CREATE tx. */
  readonly deployments: ReadonlyArray<{ readonly contractName: string; readonly address: string }>
}

/** Every chain present in broadcast/, with its product-contract deployments. */
export const DEPLOYMENTS: ReadonlyArray<ChainDeployments> = [
  {
    "chainId": 16602,
    "name": "0G Galileo Testnet",
    "explorer": "https://chainscan-galileo.0g.ai",
    "rpc": "https://evmrpc-testnet.0g.ai",
    "deployments": [
      {
        "contractName": "Access0x1Bookings",
        "address": "0x9ec3984b224057e495175aa0a6e21c1a38a7da92"
      },
      {
        "contractName": "Access0x1Escrow",
        "address": "0x93f00097e13de25090a8431d69f1cd89e1df1cf1"
      },
      {
        "contractName": "Access0x1GiftCards",
        "address": "0x8e933669a24fa6bf05206a1c17e67d5822231c6a"
      },
      {
        "contractName": "Access0x1Invoices",
        "address": "0xfd567edc7abed6e9e2cfdc8d40c4af5c8b20f4bb"
      },
      {
        "contractName": "Access0x1Nft",
        "address": "0x3af71b68612bc3facb0172eb6dcd980f50b51e86"
      },
      {
        "contractName": "Access0x1ProvenanceRegistry",
        "address": "0xbe1a9c1e8194928215045cf186283d41470abdcd"
      },
      {
        "contractName": "Access0x1Router",
        "address": "0x60eb647d166b70662e0567551af7e575f13e8008"
      },
      {
        "contractName": "Access0x1Subscriptions",
        "address": "0xd37634efeee3bc5ba16790345e7d5e15f06da69f"
      },
      {
        "contractName": "AutomationGateway",
        "address": "0x59257f3dd227a3861ab117b13a6027280490be50"
      },
      {
        "contractName": "ERC1967Proxy",
        "address": "0xd682f77d0ae016838d89b4f673f17acd93102231"
      },
      {
        "contractName": "HouseTokenFactory",
        "address": "0x4e099b81a9a46a99378ac70cad195bf8e25f0c82"
      },
      {
        "contractName": "PaymentLanes",
        "address": "0xadb6fb573afdb5519f5b0276e78791e5aa97f39f"
      },
      {
        "contractName": "SessionGrant",
        "address": "0xfd75f29369a29800fad5a5172cd8a8c4b9cc0f1b"
      }
    ]
  },
  {
    "chainId": 42431,
    "name": "Tempo Testnet (Moderato)",
    "explorer": "https://explore.testnet.tempo.xyz",
    "rpc": "https://rpc.moderato.tempo.xyz",
    "deployments": [
      {
        "contractName": "Access0x1Bookings",
        "address": "0x1db513ec23bc7de46afd6dae5133de14d8a62bf8"
      },
      {
        "contractName": "Access0x1GiftCards",
        "address": "0x1001dc04da8706d53b24389c3348ca512a5ba6b7"
      },
      {
        "contractName": "Access0x1Invoices",
        "address": "0x4e099b81a9a46a99378ac70cad195bf8e25f0c82"
      },
      {
        "contractName": "Access0x1Router",
        "address": "0x60eb647d166b70662e0567551af7e575f13e8008"
      },
      {
        "contractName": "Access0x1Subscriptions",
        "address": "0x3a43171f6d503ab314366d19b7ddc7aa861125f2"
      },
      {
        "contractName": "HouseTokenFactory",
        "address": "0x3d5247b4d5d1947c7b9c82b27f20246da9923238"
      },
      {
        "contractName": "PaymentLanes",
        "address": "0xfd75f29369a29800fad5a5172cd8a8c4b9cc0f1b"
      },
      {
        "contractName": "SessionGrant",
        "address": "0xa5982ea8842eea97c6e313a5f75fd8cf72c69aad"
      }
    ]
  },
  {
    "chainId": 43113,
    "name": "Avalanche Fuji",
    "explorer": "https://testnet.snowtrace.io",
    "rpc": "https://api.avax-test.network/ext/bc/C/rpc",
    "deployments": [
      {
        "contractName": "Access0x1Bookings",
        "address": "0x41e63263a6d78f85458dc50c9a9ea4298ed1cdfe"
      },
      {
        "contractName": "Access0x1Escrow",
        "address": "0xd682f77d0ae016838d89b4f673f17acd93102231"
      },
      {
        "contractName": "Access0x1GiftCards",
        "address": "0x3ea759f15e7edefcbfa6b55c1d3bf8a40e596909"
      },
      {
        "contractName": "Access0x1Invoices",
        "address": "0xd3ac71914d01a8229d00c2cf9abc7f93237a253d"
      },
      {
        "contractName": "Access0x1Nft",
        "address": "0x70606850d07fe7257805e8533594494dca02dcd2"
      },
      {
        "contractName": "Access0x1ProvenanceRegistry",
        "address": "0x5b2c1857c65c7daa672985fc9c3aaf2050b42288"
      },
      {
        "contractName": "Access0x1Router",
        "address": "0xc7ed3886ec8995531531cb2659d6b4bc4519c231"
      },
      {
        "contractName": "Access0x1Subscriptions",
        "address": "0xec89c9ee28af42ae2b917bb0bae245eaad6e8e57"
      },
      {
        "contractName": "AutomationGateway",
        "address": "0x5578929702b0158682286982e3f82d04a08f3b92"
      },
      {
        "contractName": "ERC1967Proxy",
        "address": "0x6602e07658214f0eaa83e857ae6f848add86a6d5"
      },
      {
        "contractName": "HouseTokenFactory",
        "address": "0xb90f34e22683d24b622a8ca32fb8cceb8ab1d505"
      },
      {
        "contractName": "PaymentLanes",
        "address": "0x065311fa0170422ee6025c2c4baa5724a5886bf0"
      },
      {
        "contractName": "SessionGrant",
        "address": "0x5ac1bc66d5073b0f84bb4f240dc2dda95cc46a6e"
      }
    ]
  },
  {
    "chainId": 46630,
    "name": "Chain 46630",
    "deployments": [
      {
        "contractName": "Access0x1Bookings",
        "address": "0x5578929702b0158682286982e3f82d04a08f3b92"
      },
      {
        "contractName": "Access0x1Escrow",
        "address": "0x5b2c1857c65c7daa672985fc9c3aaf2050b42288"
      },
      {
        "contractName": "Access0x1GiftCards",
        "address": "0xd3ac71914d01a8229d00c2cf9abc7f93237a253d"
      },
      {
        "contractName": "Access0x1Invoices",
        "address": "0x41e63263a6d78f85458dc50c9a9ea4298ed1cdfe"
      },
      {
        "contractName": "Access0x1Nft",
        "address": "0x3ea759f15e7edefcbfa6b55c1d3bf8a40e596909"
      },
      {
        "contractName": "Access0x1ProvenanceRegistry",
        "address": "0xb90f34e22683d24b622a8ca32fb8cceb8ab1d505"
      },
      {
        "contractName": "Access0x1Router",
        "address": "0xf0056b52df2cc2aa3e80e607a0770b062ba737d5"
      },
      {
        "contractName": "Access0x1Subscriptions",
        "address": "0xd682f77d0ae016838d89b4f673f17acd93102231"
      },
      {
        "contractName": "AutomationGateway",
        "address": "0xec89c9ee28af42ae2b917bb0bae245eaad6e8e57"
      },
      {
        "contractName": "ERC1967Proxy",
        "address": "0x2ba5411803bc7734652afa292bc97f39ae409f76"
      },
      {
        "contractName": "HouseTokenFactory",
        "address": "0x1fecfe4781e9a38b4291b681751e048cc6d1eac5"
      },
      {
        "contractName": "PaymentLanes",
        "address": "0x5ac1bc66d5073b0f84bb4f240dc2dda95cc46a6e"
      },
      {
        "contractName": "SessionGrant",
        "address": "0xc7ed3886ec8995531531cb2659d6b4bc4519c231"
      }
    ]
  },
  {
    "chainId": 84532,
    "name": "Base Sepolia",
    "explorer": "https://sepolia.basescan.org",
    "rpc": "https://sepolia.base.org",
    "deployments": [
      {
        "contractName": "Access0x1Bookings.impl",
        "address": "0xad3dbc884d29ea749f2ac16178b0fdac66acb6b4"
      },
      {
        "contractName": "Access0x1Bookings.proxy",
        "address": "0xa7230ddd55c6bfc3479636fa320e46889a8b1863"
      },
      {
        "contractName": "Access0x1Escrow.impl",
        "address": "0xf87c5619d8906811fcd3945b56bfb6d45d2f3730"
      },
      {
        "contractName": "Access0x1Escrow.proxy",
        "address": "0x3459e890516a29d406fcbdc9b4cd99ce8114da0d"
      },
      {
        "contractName": "Access0x1GiftCards.impl",
        "address": "0x7d591535d56da5ca1b178553a443b49084a78f55"
      },
      {
        "contractName": "Access0x1GiftCards.proxy",
        "address": "0xf94df7293e48e69f91a1e2c4f48580c6901d6c2c"
      },
      {
        "contractName": "Access0x1Invoices.impl",
        "address": "0x16188291f27bb820da27c64b852277a62a6475fa"
      },
      {
        "contractName": "Access0x1Invoices.proxy",
        "address": "0x902382d472aaf6bd90e000c315a861f6b493bcea"
      },
      {
        "contractName": "Access0x1Nft.impl",
        "address": "0x13a80b7543a0caed7e64281109b2c1ac25677d07"
      },
      {
        "contractName": "Access0x1Nft.proxy",
        "address": "0x9625bec5e2ed53b48e4cbcbbbe9287c00db31178"
      },
      {
        "contractName": "Access0x1ProvenanceRegistry.impl",
        "address": "0xacc0a130e1366a2e3a9fe7932a7b424d906487bb"
      },
      {
        "contractName": "Access0x1ProvenanceRegistry.proxy",
        "address": "0x899b9e0b633bc46f56d7ec34ad667147d8e68ceb"
      },
      {
        "contractName": "Access0x1Router.impl",
        "address": "0x3336ec82d865e8bd1f9054856ac22b45a71207db"
      },
      {
        "contractName": "Access0x1Router.proxy",
        "address": "0xe92244e3368561faf21648146511dede3a475eb5"
      },
      {
        "contractName": "Access0x1Subscriptions.impl",
        "address": "0xd0f21319739cfd94989ab68d69a4268ff141f1ee"
      },
      {
        "contractName": "Access0x1Subscriptions.proxy",
        "address": "0x787d2d97f7b0b0a7afe1ecd97032912fefe8e0ba"
      },
      {
        "contractName": "AutomationGateway.impl",
        "address": "0x39e3ffa33873f89f4a3c18383f663d177e65031a"
      },
      {
        "contractName": "AutomationGateway.proxy",
        "address": "0x2b664ca5a28498cc62b475576fee6835dd51060b"
      },
      {
        "contractName": "HouseTokenFactory.impl",
        "address": "0x86cbc26a3d20d0d4f4bd89f56ac34906cbb091c0"
      },
      {
        "contractName": "HouseTokenFactory.proxy",
        "address": "0x5a7f065f675779d76a376c15be496d799b1469db"
      },
      {
        "contractName": "PaymentLanes.impl",
        "address": "0x6312b40510c0718d2e7b8a9a6490b4fc6a4dfe9f"
      },
      {
        "contractName": "PaymentLanes.proxy",
        "address": "0x49bb2c3d3aae0ad260f3ce76fa78e0323aae2510"
      },
      {
        "contractName": "SessionGrant.impl",
        "address": "0x7c59aa000904efc5e15b03081963f7e406424d7f"
      },
      {
        "contractName": "SessionGrant.proxy",
        "address": "0xf84fea541939f3683893530101fe77d05c390c9d"
      }
    ]
  },
  {
    "chainId": 560048,
    "name": "Hoodi",
    "explorer": "https://hoodi.etherscan.io",
    "rpc": "https://rpc.hoodi.ethpandaops.io",
    "deployments": [
      {
        "contractName": "Access0x1Bookings",
        "address": "0x1db513ec23bc7de46afd6dae5133de14d8a62bf8"
      },
      {
        "contractName": "Access0x1GiftCards",
        "address": "0x1001dc04da8706d53b24389c3348ca512a5ba6b7"
      },
      {
        "contractName": "Access0x1Invoices",
        "address": "0x4e099b81a9a46a99378ac70cad195bf8e25f0c82"
      },
      {
        "contractName": "Access0x1Router",
        "address": "0x60eb647d166b70662e0567551af7e575f13e8008"
      },
      {
        "contractName": "Access0x1Subscriptions",
        "address": "0x3a43171f6d503ab314366d19b7ddc7aa861125f2"
      },
      {
        "contractName": "HouseTokenFactory",
        "address": "0x3d5247b4d5d1947c7b9c82b27f20246da9923238"
      },
      {
        "contractName": "PaymentLanes",
        "address": "0xfd75f29369a29800fad5a5172cd8a8c4b9cc0f1b"
      },
      {
        "contractName": "SessionGrant",
        "address": "0xa5982ea8842eea97c6e313a5f75fd8cf72c69aad"
      }
    ]
  },
  {
    "chainId": 5042002,
    "name": "Arc Testnet",
    "rpc": "https://rpc.testnet.arc.network",
    "deployments": [
      {
        "contractName": "Access0x1Bookings",
        "address": "0x2067238186ee13d9c543742e1bb6be9fe4a1b20b"
      },
      {
        "contractName": "Access0x1Escrow",
        "address": "0x41f671f29ebd14fca6d8355e97f48d92ab4573a9"
      },
      {
        "contractName": "Access0x1GiftCards",
        "address": "0x2ba5411803bc7734652afa292bc97f39ae409f76"
      },
      {
        "contractName": "Access0x1Invoices",
        "address": "0xbcb59e981662d26769ff1fe5d75f66e38c68c99b"
      },
      {
        "contractName": "Access0x1Nft",
        "address": "0x6602e07658214f0eaa83e857ae6f848add86a6d5"
      },
      {
        "contractName": "Access0x1ProvenanceRegistry",
        "address": "0x3af71b68612bc3facb0172eb6dcd980f50b51e86"
      },
      {
        "contractName": "Access0x1Router",
        "address": "0xd37634efeee3bc5ba16790345e7d5e15f06da69f"
      },
      {
        "contractName": "Access0x1Subscriptions",
        "address": "0xf5d9eefb2e3abbfb9ae2b4e6a26d170de7ad12c6"
      },
      {
        "contractName": "AutomationGateway",
        "address": "0xa888a802826b08c307a252fe8b948e411dcbf835"
      },
      {
        "contractName": "ERC1967Proxy",
        "address": "0xc93bd2808fadfe87ea40a90db8fded3e09d266a4"
      },
      {
        "contractName": "HouseTokenFactory",
        "address": "0x8e933669a24fa6bf05206a1c17e67d5822231c6a"
      },
      {
        "contractName": "PaymentLanes",
        "address": "0x9ec3984b224057e495175aa0a6e21c1a38a7da92"
      },
      {
        "contractName": "SessionGrant",
        "address": "0x59257f3dd227a3861ab117b13a6027280490be50"
      }
    ]
  },
  {
    "chainId": 11155111,
    "name": "Sepolia",
    "explorer": "https://sepolia.etherscan.io",
    "rpc": "https://11155111.rpc.thirdweb.com",
    "deployments": [
      {
        "contractName": "Access0x1Bookings",
        "address": "0xfd36dade3c7c4cb496c92568b0c90afdb6eb989c"
      },
      {
        "contractName": "Access0x1Escrow",
        "address": "0x5af67cdbd3fa95d92091943a94c9e11d20cd6ba9"
      },
      {
        "contractName": "Access0x1GiftCards",
        "address": "0x31cc4997f01bbe9e13b42bd71c55e0163eab4ed6"
      },
      {
        "contractName": "Access0x1Invoices",
        "address": "0xe8063cfe04faf314ae048788da3baad1fc293401"
      },
      {
        "contractName": "Access0x1Nft",
        "address": "0x9ff0ba26c311fb3c42597de06fee2f614f60d761"
      },
      {
        "contractName": "Access0x1ProvenanceRegistry",
        "address": "0x877e63f93e3934939f9bbfbd77ca4e13055a6d51"
      },
      {
        "contractName": "Access0x1Router",
        "address": "0xb3b3b3981d0ba22945e4cf9659e133eb4e1eedb6"
      },
      {
        "contractName": "Access0x1Subscriptions",
        "address": "0x3c3f42eb179a24a93663cba6e21f0bb166bd142b"
      },
      {
        "contractName": "AutomationGateway",
        "address": "0x75a3095be2d5ad9ea7a68a1b098773cd72819679"
      },
      {
        "contractName": "ERC1967Proxy",
        "address": "0x67072815258ebfd5b99c21140a3816e368d1e855"
      },
      {
        "contractName": "HouseTokenFactory",
        "address": "0x61ed29abe4bb0a525d96ba91410fee7ac030bf5e"
      },
      {
        "contractName": "PaymentLanes",
        "address": "0x1462c19fe2b34a3bf83e0bde2ab65ca511860c8c"
      },
      {
        "contractName": "SessionGrant",
        "address": "0x082c79051bea1d8bcdf71faf386db7d75ad32608"
      }
    ]
  },
  {
    "chainId": 11155420,
    "name": "OP Sepolia",
    "explorer": "https://optimism-sepolia.blockscout.com",
    "rpc": "https://sepolia.optimism.io",
    "deployments": [
      {
        "contractName": "Access0x1Bookings",
        "address": "0x93cb11ce74d45a1b554007cd43c2a96fb830b113"
      },
      {
        "contractName": "Access0x1Escrow",
        "address": "0x994011ff20df033fb35e67fedfb17f647bf66635"
      },
      {
        "contractName": "Access0x1GiftCards",
        "address": "0xe654209f302b3767455f3527b8dd50a5174a162b"
      },
      {
        "contractName": "Access0x1Invoices",
        "address": "0xdea2b9d695f92ffea246ff0a01bdcb1ff37d86b3"
      },
      {
        "contractName": "Access0x1Nft",
        "address": "0xfd714779a732770ca0eb14f95769b63542e3ac9f"
      },
      {
        "contractName": "Access0x1ProvenanceRegistry",
        "address": "0x2d6b08eb73898036eee756351453b08188d92c56"
      },
      {
        "contractName": "Access0x1Router",
        "address": "0x2d957e2c63799bf3ed05d3231bb80bd338c893fd"
      },
      {
        "contractName": "Access0x1Subscriptions",
        "address": "0x025f098873557105259b81618f05e09c833fd705"
      },
      {
        "contractName": "AutomationGateway",
        "address": "0x81ca26e3fb738661d44d5ad89280fb32848038e8"
      },
      {
        "contractName": "ERC1967Proxy",
        "address": "0x8cdddf8a426ac79a2accc83e6b63fb16eb7580e2"
      },
      {
        "contractName": "HouseTokenFactory",
        "address": "0xae5018d227af3a7778bebed85112a62f802e6b01"
      },
      {
        "contractName": "PaymentLanes",
        "address": "0xb71fe836cc8c698ea0fa150deed6cd33ad352c85"
      },
      {
        "contractName": "SessionGrant",
        "address": "0x4fbf47bc5273491b8a4e339e65b208d180b27c3b"
      }
    ]
  }
] as const
