#!/usr/bin/env bash
# storage-layout.sh — regenerate docs/STORAGE-LAYOUT.md from `forge inspect <C> storage-layout`.
#
# Auditors verify the storage layout of the money contracts: that slots pack as the comments claim,
# that no two variables collide, and that the layout does not drift unexpectedly between versions.
# This script captures the layout of the contracts that hold value-bearing state, in one doc.
#
# Run via `make storage-layout`. Foundry must be on PATH (the Makefile prepends ~/.foundry/bin).
set -euo pipefail

OUT="docs/STORAGE-LAYOUT.md"

# The value-bearing / stateful first-party contracts an auditor checks. NameMath (pure, no state),
# the interfaces, and OracleLib (an inlined internal library) are intentionally excluded.
CONTRACTS=(
  # Money spine + identity/registry
  "src/Access0x1Router.sol:Access0x1Router"
  "src/PaymentLanes.sol:PaymentLanes"
  "src/ChainRegistry.sol:ChainRegistry"
  "src/SessionGrant.sol:SessionGrant"
  "src/PriceOracleAdapter.sol:PriceOracleAdapter"
  # Commerce set
  "src/Access0x1Subscriptions.sol:Access0x1Subscriptions"
  "src/Access0x1Bookings.sol:Access0x1Bookings"
  "src/Access0x1Invoices.sol:Access0x1Invoices"
  "src/Access0x1GiftCards.sol:Access0x1GiftCards"
  # Settlement / money-movement extensions
  "src/Access0x1Escrow.sol:Access0x1Escrow"
  "src/Receivables.sol:Receivables"
  "src/Refunds.sol:Refunds"
  "src/SplitSettler.sol:SplitSettler"
  "src/GaslessPayIn.sol:GaslessPayIn"
  "src/Access0x1Receiver.sol:Access0x1Receiver"
  "src/AutomationGateway.sol:AutomationGateway"
  # Assets / provenance
  "src/Access0x1Nft.sol:Access0x1Nft"
  "src/Access0x1ProvenanceRegistry.sol:Access0x1ProvenanceRegistry"
  "src/HouseToken.sol:HouseToken"
  "src/HouseTokenFactory.sol:HouseTokenFactory"
)

{
  echo "# Access0x1 — Storage Layout"
  echo
  echo "> Generated by \`make storage-layout\` (\`forge inspect <C> storage-layout\`). Auditors use this"
  echo "> to verify slot packing, the absence of collisions, and that the layout does not drift"
  echo "> unexpectedly between versions. Pure (\`NameMath\`), interface, and inlined-library"
  echo "> (\`OracleLib\`) types are excluded — they hold no storage."
  echo
  echo "Toolchain: \`forge\` (solc 0.8.28, EVM cancun, via_ir). Regenerate after any storage change."
  echo
  for c in "${CONTRACTS[@]}"; do
    name="${c##*:}"
    echo "## ${name}"
    echo
    echo '```json'
    forge inspect "$c" storage-layout --json 2>/dev/null || forge inspect "$c" storage-layout
    echo '```'
    echo
  done
} > "$OUT"

echo "==> wrote ${OUT} for ${#CONTRACTS[@]} contracts"
